stages:
  - setup
  - validation
  - test
  - build
  - deploy

variables:
  DEV_IMAGE: "$ECR_URI:dev"
  PROD_IMAGE: "$ECR_URI:$CI_COMMIT_TAG"

deploy:
  stage: deploy
  before_script:
      - curl -s https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | bash
      - chmod 600 .secure_files/trinity-dev-key-pair.pem
      - ssh-keyscan -H $EC2_PUBLIC_IP >> ~/.ssh/known_hosts
  script:
    - chmod +x deploy.sh
    - ./deploy.sh
  tags:
    - shell-executor
  only:
    - develop
  environment:
    name: Dev
