stages:
  - setup
  - validation
  - test
  - build
  - deploy

default:
  tags:
    - backend-docker
  image: node:20

setup:
  stage: setup
  script:
    - echo "Installation des dépendances"
    - npm ci
  artifacts:
    paths:
      - node_modules/
    expire_in: 1h

scan-sensitive-informations:
  stage: validation
  tags:
    - backend-docker
  image: alpine
  before_script:
    - apk add --no-cache git make bash
    - git clone https://github.com/awslabs/git-secrets.git
    - cd git-secrets && make install && cd ..
  script:
    - echo "Vérification des infos sensibles"
    - git secrets --scan

lint:
  stage: validation
  dependencies:
    - setup
  script:
    - echo "Analyse du code source"
    - npm run lint

test:
  stage: test
  dependencies:
    - setup
  script:
    - echo "Exécution des tests unitaires"
    - npm run test
  artifacts:
    paths:
      - test-results/test-report.xml
    reports:
      junit: test-results/test-report.xml

test-coverage:
  stage: test
  dependencies:
    - setup
  script:
    - echo "Analyse de la couverture de code"
    - npm run test:cov
  artifacts:
    paths:
      - coverage/

build:
  stage: build
  dependencies:
    - setup
  script:
    - echo "Compilation et construction du code source"
    - npm run build
  artifacts:
    paths:
      - dist/

build-image:
  stage: build
  tags:
    - backend
  before_script: []
  script:
    - docker build -t $IMAGE_NAME .
  only:
    - develop

tag-image:
  stage: build
  tags:
    - backend
  before_script: []
  script:
    - docker tag $IMAGE_NAME $ECR_URI:latest
  only:
    - develop

push-image:
  stage: build
  tags:
    - backend
  before_script: []
  script:
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URI
    - docker push $ECR_URI:latest
  only:
    - develop