version: '3.8'

services:
  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 4g
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elastic-network

  # Kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.1
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elastic-network

  # Filebeat
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.7.1
    container_name: filebeat
    user: root
    entrypoint: ["/usr/share/filebeat/entrypoint.sh"]
    volumes:
      - ./deployment/monitoring/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./logs:/usr/share/filebeat/logs
      - ./deployment/monitoring/filebeat-entrypoint.sh:/usr/share/filebeat/entrypoint.sh:ro
    depends_on:
      - elasticsearch
    networks:
      - elastic-network

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:8.7.1
    container_name: metricbeat
    user: root
    entrypoint: ["/usr/share/metricbeat/entrypoint.sh"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./deployment/monitoring/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
      - ./deployment/monitoring/metricbeat-entrypoint.sh:/usr/share/metricbeat/entrypoint.sh:ro
    depends_on:
      - elasticsearch
    networks:
      - elastic-network

networks:
  elastic-network:
    driver: bridge
